"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-session' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex",
    "scitex.utils._notify",
    "scitex_clew",
    "scitex_dev",
    "scitex_dict",
    "scitex_gen._detect_notebook_path",
    "scitex_io",
    "scitex_io._flush",
    "scitex_io._load",
    "scitex_io._save",
    "scitex_logging",
    "scitex_repro",
    "scitex_str",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_module_import_returns_module_object(module_name):
    # Arrange
    pytest.importorskip(module_name)
    # Act
    mod = importlib.import_module(module_name)
    # Assert
    assert mod.__name__ == module_name
