"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-session' references
in its source tree. Renames or moves in peer standalones (or in the
umbrella's deep-import surface) surface as a hard failure here — not
as a silent ModuleNotFoundError when an end user runs the CLI.
"""
import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex',
    'scitex.utils._notify',
    'scitex_clew',
    'scitex_dev._analyze_code_flow',
    'scitex_dict',
    'scitex_gen._detect_notebook_path',
    'scitex_io',
    'scitex_io._flush',
    'scitex_io._load',
    'scitex_io._save',
    'scitex_logging',
    'scitex_plt',
    'scitex_repro',
    'scitex_str',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-session's declared cross-package dependency must succeed."""
    importlib.import_module(module_name)
