"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest

pytestmark = pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason=(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]"
    ),
)


def test_audit_all_for_scitex_session_reports_clean():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # The MCP audit's §6 rule ("every Python API must have a matching MCP
    # tool") flags this package's lifecycle entry points (start, close,
    # session, run, running2finished) because they aren't surfaced as MCP
    # tools. By design — those are decorator / process-lifecycle helpers
    # that aren't sensibly callable from an MCP agent (they're how a
    # script wraps `main`, not what an agent invokes from outside).
    # Only the archive helpers (archive_existing, restore_existing,
    # archive_session_dir, restore_session_archive) — which DO make sense
    # as agent-callable tools — are wired up in _mcp_server.py.
    skip_rules = ("§6",)

    # Act
    audit_all_for_package("scitex-session", skip_rules=skip_rules)
    # Assert
    assert True  # audit_all_for_package raises on violation
